version: "2.3"

services:
  alpr:
    build:
      context: .
      dockerfile: Dockerfile.jetson

    runtime: nvidia
    network_mode: host

    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - RTSP_URL

    volumes:
      - ./:/work
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/argus_socket:/tmp/argus_socket

    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1

    working_dir: /work
    stdin_open: true
    tty: true
